name: first_app
description: A Flutter starter app that gives you a solid foundation for a real app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.6.9+26

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #intl: ^0.18.1
  oauth2_client: ^3.0.0
  cupertino_icons: ^1.0.5
  meta: ^1.7.0
  http: ^0.13.5
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  google_maps_flutter: ^2.2.6
  google_maps_flutter_web: ^0.4.0+3
  geocoding: ^2.0.5
  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.8
  firebase_crashlytics: ^3.0.8
  firebase_messaging: ^14.2.0
  geolocator: ^9.0.1
  mockito: ^5.3.2
  location: ^4.4.0
  eventsource: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4
  flutter_launcher_icons: ^0.11.0
  convert: ^3.0.2
  google_maps_widget: ^1.0.5+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
    - assets/img/taiebbb.jpg
    - assets/img/bolt.png
    - assets/img/down_orange.png
    - assets/img/fish.png
    - assets/img/illustration.png
    - assets/img/sausage.png
    - assets/img/shoe.png
    - assets/img/up_red.png
    - assets/fitness_app/
    - assets/img/car.jpg
    - assets/img/car_icon.png 
    - assets/fitness_app/kilometrique.jfif
    
   
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf

  # Enable generation of localized Strings from arb file AppLocalizations.
  generate: true
